const config = require('../../config.json');

const EMOTES = {
  success: config.emotes.success,
  error: config.emotes.error,
  loading: config.emotes.loading,
  info: config.emotes.info,
  warning: config.emotes.warning
};

// Borrowed from https://github.com/solo-studios/PolyBot/blob/feature/plugins/src/main/resources/default.conf#L41
const slurs = [
  "(n|m|j|sm|sn|fl|ch|pr)(i|e)+gg?(rs?|ett?e?s?|lets?|ress?e?s?|r(a|o|e)s?|(i|e|a|o|u)rs?|roids?|abos?|erest|(a|u|e)hs?)",
  "(ph|f)agg?s?((e|a|i|o)ts?|oted|otry)",
  "(ph|f)ags?",
  "(re)?tards?",
  "(shit|mud) skins?",
  "(towel|rag) heads?",
  "african'?t",
  "ape fricans?",
  "beane(r|y)s?",
  "blacky chan",
  "chimpires?",
  "china m(a|e)n",
  "ching chong",
  "chink",
  "cock suckers?",
  "coons? (ass|town)",
  "coons?(y|er)",
  "cunt boys?",
  "cunts?y?",
  "darke?ys?",
  "dick girls?",
  "dog eaters?",
  "dot heads?",
  "dune coone?r?s?",
  "dyk(e|on)",
  "fagg?(ot|y|et|otry)?s?",
  "fuck (wits?|tards?)",
  "fuck boys?",
  "g(ooks?|00ks?)",
  "gringo",
  "groids?",
  "gypp?(ie|o|y|sy",
  "he female",
  "jew boy",
  "jew fag",
  "jigg?(a|e|r)+(boing)",
  "jigg?(a|e|r)+boo?s?",
  "kykes?",
  "lady boys?",
  "le(sbo|zz?y)s?",
  "mignorants?",
  "mud childr?e?n?",
  "nig town",
  "nigg?(a|e|o|i)?s?",
  "pakys?",
  "pansys?",
  "porch monke?ys?",
  "pussys?",
  "redskin",
  "retards?(ed|edly)",
  "she m(a|e)n",
  "she males?",
  "shee? boons?",
  "siss?yies?",
  "spics?",
  "tarbabys?",
  "ting tong",
  "trann?ys?",
  "trans fag",
  "wet backs?",
  "lesbos?",
  "penis(es)?",
  "cocks?",
  "whores?",
  "sluts?",
  "bitch(es)?",
  "cum",
  "pussy",
  "anal",
  "anus",
  "clitoris",
  "dildo"
];

module.exports = {
  EMOTES,
  slurs
};